# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

use_frameworks!

target 'Brew Week' do

pod 'SwiftyJSON', '~> 2.3.2'
pod 'Alamofire', '~> 3.3.1'

end

target 'Brew WeekTests' do

end

