# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

use_frameworks!

target 'Brew Week' do

pod 'SwiftyJSON', '~> 2.2'
pod 'AlamoFire', '~> 1.2'

end

target 'Brew WeekTests' do

end

